[General]
%23%202=GOTO_ADJACENT: at the last image, next goes to the next folder's first
JPEGSaveQuality=95
autoResizeLimit=90
autoResizeWindow=false
backgroundOpacity=1
blurBackground=false
clickableEdges=false
clickableEdgesVisible=true
confirmDelete=false
confirmTrash=false
cursorAutohiding=true
defaultCropAction=0
defaultFitMode=0
defaultViewMode=0
drawTransparencyGrid=false
enableSmoothScroll=true
expandImage=true
expandLimit=2
firstRun=false
fixedZoomLevels="0.05,0.1,0.125,0.166,0.25,0.333,0.5,0.66,1,1.5,2,3,4,5,6,7,8"
focusPointIn1to1Mode=1
folderEndAction=2
folderViewIconSize=120
imageScrolling=1
infoBarFullscreen=true
infoBarWindowed=false
jxlAnimation=false
keepFitMode=true
language=en_US
lastVerMajor=1
lastVerMicro=3
lastVerMinor=0
loopSlideshow=false
memoryAllocationLimit=1024
mouseScrollingSpeed=@Variant(\0\0\0\x87?\x80\0\0)
mpvBinary=/usr/bin/mpv
openInFullscreen=true
panelCenterSelection=false
panelEnabled=true
panelFullscreenOnly=true
panelPinned=false
panelPosition=top
panelPreviewsSize=170
playVideoSounds=true
scalingFilter=3
showHiddenFiles=false
showSaveOverlay=true
slideshowInterval=3000
smoothAnimatedImages=true
smoothUpscaling=true
sortFolders=true
sortingMode=0
squareThumbnails=false
thumbPanelStyle=1
thumbnailCache=true
thumbnailerThreads=4
trackpadDetection=true
unloadThumbs=true
unlockMinZoom=true
useFixedZoomLevels=false
usePreloader=true
useSystemColorScheme=false
videoPlayback=true
windowTitleExtendedInfo=true
zoomIndicatorMode=0
zoomStep=@Variant(\0\0\0\x87>L\xcc\xcd)

[Controls]
shortcuts="zoomIn=+", "zoomOut=-", "fitWindow=1", "fitWidth=2", "fitNormal=3", "goUp=Backspace", "copyFile=C", "moveToTrash=Del", "scrollDown=Down", "jumpToLast=End", "folderView=Enter", "closeFullScreenOrExit=Esc", "toggleFullscreen=F", "toggleFullscreen=F11", "renameFile=F2", "reloadImage=F5", "flipH=H", "jumpToFirst=Home", "toggleImageInfo=I", "nextImage=J", "prevImage=K", "s:Favorite=L", "toggleFullscreen=LMB_DoubleClick", "prevImage=Left", "moveFile=M", "contextMenu=Menu", "exit=MiddleButton", "openSettings=P", "resize=R", "contextMenu=RMB", "nextImage=Right", "toggleFitMode=Space", "scrollUp=Up", "flipV=V", "nextImage=WheelDown", "prevImage=WheelUp", "crop=X", "prevImage=XButton1", "nextImage=XButton2"

[Scripts]
1\command=/usr/local/bin/fav %file%
1\name=Favorite
script\1\name=Favorite
script\1\value=@Variant(\0\0\0\x7f\0\0\0\aScript\0\0\0\0\x32\0/\0u\0s\0r\0/\0l\0o\0\x63\0\x61\0l\0/\0\x62\0i\0n\0/\0\x66\0\x61\0v\0 \0%\0\x66\0i\0l\0\x65\0%\0)
script\size=1
