---
# 软件包管理 (APT, Snap, Flatpak)

- name: 绕过 dirmngr 获取 Kubuntu Backports GPG 密钥
  ansible.builtin.get_url:
    url: "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7EB726D45F5037D1A642C72C17FB29293721A2CD"
    dest: /etc/apt/keyrings/kubuntu-ppa.asc
    mode: '0644'

- name: 显式添加 Kubuntu Backports 源以获取最新 KWin/Plasma 修复 (Nvidia 刚需)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubuntu-ppa.asc] http://ppa.launchpadcontent.net/kubuntu-ppa/backports/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: kubuntu-ppa-backports
- name: 强制系统全量升级 (涵盖 PPA 及灰度更新)
  ansible.builtin.apt:
    upgrade: full
    update_cache: yes

- name: 安装核心开发与实用工具
  ansible.builtin.apt:
    name:
      - build-essential
      - curl
      - git
      - docker.io
      - ripgrep
      - eza
      - unzip
      - htop
      - kitty
      - qimgv
      - rsync
      - stow
    state: present
    update_cache: yes

- name: 安装极简 KDE 桌面环境 (针对 Server 镜像)
  ansible.builtin.apt:
    name:
      - kde-plasma-desktop
      - sddm
      - xwayland
    state: present

- name: 安装桌面环境核心组件 (Fcitx5 输入法及相关依赖)
  ansible.builtin.apt:
    name:
      - fcitx5
      - fcitx5-config-qt
      - fcitx5-chinese-addons
      - fcitx5-rime
      - nvidia-vaapi-driver
    state: present

- name: 安装全局 Flatpak 软件
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
  loop:
    # 这里可以直接读取原先配置里的列表，作为演示先写死几个
    - org.mozilla.firefox

- name: 安装局域网定制工具 (CC-Switch 等，如果安装包存在)
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop:
    - "/usr/local/share/provisioner-ubuntu/config/cc-switch.deb"
