[Audio]
Volume=100

[General]
LastPlayedFile=file:///mnt/ssd1t/porn/18岁梦涵宝贝合集高清直播视频102部 102V 78.9G/18岁梦涵 20220300 18岁梦涵 (1).mp4

[Playback]
HWDecoding=nvdec-copy

[Playlist]
PlaybackBehavior=StopAfterLast
Visible=true

[Video]
ScreenshotFormat=png
