[Shortcuts]
playNextAction=PgDown
playPreviousAction=PgUp
playbackSpeedDecreaseAction=X
playbackSpeedIncreaseAction=C
playbackSpeedResetAction=Z
seekNextChapterAction=
seekPreviousChapterAction=
subtitleQuickenAction=
