# 退出时永远自动保存播放进度
save-position-on-quit=yes

# 开启硬件解码
hwdec=no

# 截图设置 (类似 PotPlayer: 文件名-[时.分.秒])
screenshot-format=png
screenshot-template="%F-[%wH.%wM.%wS]"
screenshot-directory="~/Pictures"

# 优化硬解和机械硬盘下的快进/拖动流畅度 (放弃精准寻帧，换取极速响应)
hr-seek=no
hr-seek-framedrop=yes

# 机械硬盘究极优化：开启激进的内存大缓存 (强制将硬盘数据预读到内存中)
cache=yes
demuxer-max-bytes=1000MiB
demuxer-max-back-bytes=200MiB
