---
- name: Ubuntu 极客开发机自动化装机剧本 (Provisioning Playbook)
  hosts: localhost
  connection: local
  become: yes  # 默认提权，对于特定用户级别的操作在 task 内部用 become: no 或者 become_user 指定

  tasks:
    - name: 执行网络与源配置
      ansible.builtin.import_tasks: tasks/network.yml

    - name: 执行基础系统与安全配置
      ansible.builtin.import_tasks: tasks/system.yml

    - name: 执行软件包安装
      ansible.builtin.import_tasks: tasks/packages.yml

    - name: 执行桌面与输入法配置 (降权使用当前用户)
      ansible.builtin.import_tasks: tasks/desktop.yml
      become: no

    - name: 执行极客开发套件配置
      ansible.builtin.import_tasks: tasks/dev_tools.yml

    - name: 执行用户级配置同步 (降权)
      ansible.builtin.import_tasks: tasks/user.yml
      become: no
