---
- name: Ubuntu 极客开发机自动化装机剧本 (Provisioning Playbook)
  hosts: localhost
  connection: local
  become: yes
  vars:
    target_user: "dropguard"  # 强制锁定日常用户名


  tasks:
    - name: 执行网络与源配置
      ansible.builtin.import_tasks: tasks/network.yml

    - name: 执行基础系统与安全配置
      ansible.builtin.import_tasks: tasks/system.yml

    - name: 执行软件包安装
      ansible.builtin.import_tasks: tasks/packages.yml

    - name: 执行桌面与输入法配置
      ansible.builtin.import_tasks: tasks/desktop.yml
      become_user: "{{ target_user }}"


    - name: 执行极客开发套件配置
      ansible.builtin.import_tasks: tasks/dev_tools.yml
      become_user: "{{ target_user }}"

    - name: 执行用户级配置同步
      ansible.builtin.import_tasks: tasks/user.yml
      become_user: "{{ target_user }}"

